### ISSUE TITLE
Flickering of some random subtitles

### ISSUE THREAD

**Issue by JSP99** [SunnyLi/videojs-ass#3] opened 2015-07-28 10:14 UTC
**Browser:** Mozilla Firefox 39.0
When the demo video is rendered, few random subtitles are 'flickering'. I checked it on another video with my own `.ass` subtitle file, and the issue persists. But just so that it's convenient for you to verify, here is an example:

**Example:** In the demo video (duration `3:36`), observe the frames from  (`0:32` to `0:40`). All the subtitles except the last one (in the frames from `0:32` to `0:40`) are rendered properly. The last subtitle 'flickers'. It **is** rendered as expected. But it vanishes for a moment and then reappears again.  The subtitle line reads *"What loathsome tales"*.  
![bug](https://cloud.githubusercontent.com/assets/4367666/8928782/068897c4-3521-11e5-910e-c75ab7e8301d.png)

This flickering issue is not so noticeable in your demo video. But in some other videos, this is highly noticeable and hinders the efficiency of the plugin.

I am not sure if this is some problem specific to my software environment.
PS: I love `videojs-ass`

**Comment by SunnyLi** [comment] 2015-07-29 04:32
Hi, you have an interesting find.

It seems like this issue is caused by `videojs`'s time tracking variable not always being able to update before each `libjass` time update query loop, causing `libjass` to seek back in time when it receives the repeated time. Thus causing the subtitle to reappear.

If this is the cause (hopefully), then it has been fixed in Arnavion/libjass@0b4c66f88a and will be fixed here once `libjass` release its next version.

**Comment by JSP99** [comment] 2015-07-29 10:06
Ohh thanks. I will be waiting for this fix.

**Comment by SunnyLi** [comment] 2015-09-07 23:39
So I did a small update and I believe that by lowering libjass' clock rate down to some value like `0.95` or lower will help to avoid this problem for now until the actual fix comes in.

Changing the clock rate shouldn't be much of a problem as the clock will sync to the real video time every animation frame or so, this is just to prevent the clock from actually ticking ahead of the actual time and reverting back thus causing this issue.

Here's how you can change the rate:
```
      videojs('player_id', {
        controls: true,
        plugins: {
          ass: {
            'src': ["..."],
            'rate': 0.95
          }
        }
      });
```

**Comment by Arnavion** [comment] 2016-01-08 18:17
Actually what's happening is that the code that removes the sub when currentTime > dialogue's end time runs at some small time greater than the dialogue's end time. Since [libjass stopped setting animation-fill-mode to `both`,](https://github.com/Arnavion/libjass/commit/72df7fc) it defaults to `none`. That means that after the fade-out ends the line will go back to full opacity before it gets removed, hence the flash.

The clock rate is used for calculating the time for animations to run, so by setting it to 0.95 you're making libjass run the fade-out at 95% speed, so it stays faded out until the sub gets a chance to be removed. That does solve the flickering problem but it changes the timing for all animations, so it's not an ideal solution.

I *think* that since fade is only represented by one animation now instead of two, it should be possible to use `animation-fill-mode: both` again. I'll test.

**Comment by Arnavion** [comment] 2016-01-15 09:38
I confirmed that add the animation-fill-mode back to the `.libjass-subs, .libjass-subs *` rule in libjass.css:

```css
.libjass-subs, .libjass-subs * {
	pointer-events: none;
+	-webkit-animation-fill-mode: both;
+	animation-fill-mode: both;
}
```

solves the flashing problem. If you don't want to wait for 0.11.0 release you can make that change in libjass.css yourself.

**Comment by SunnyLi** [comment] 2016-01-18 06:21
@Arnavion Thanks for the solve :+1:

I've included the fix in `videojs.ass.css` for now since it's a small change.

**Closed** 2016-01-21 05:57 UTC
